openapi: 3.2.0
info:
  title: Defacto Subscription API
  version: v1.0.0
  description: Defacto provides instant, embedded financing for SMBs across Europe.
  contact:
    email: contact@getdefacto.com
    url: https://developers.getdefacto.com/
servers:
- url: https://api.getdefacto.com
  description: Production
- url: https://api-sandbox.getdefacto.com
  description: Sandbox
security:
- Bearer: []
tags:
- name: Subscription
paths:
  /subscription/{subscription_id}/activate:
    post:
      description: Activate a subscription.
      parameters:
      - in: path
        name: subscription_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Subscription activated
        '400':
          description: Subscription is not in an activatable state
        '404':
          description: Subscription not found
      security:
      - Bearer: []
      tags:
      - Subscription
      operationId: post_subscription-subscription-id-activate
      summary: /subscription/{subscription_id}/activate
components:
  securitySchemes:
    Bearer:
      in: header
      name: Authorization
      type: apiKey
